name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: "Test, Lint, and Report Coverage to Codecov"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install Locked Dependencies
        run: npm ci
      - name: Test
        run: npm test
      - name: Lint
        run: npm run lint
      - name: Generate Coverage Report
        run: npm run coverage
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/
          fail_ci_if_error: true
